### ISSUE TITLE
支持一下大佬

### ISSUE THREAD

**Issue by VoidK2** [gesangtome/android_kernel_nubia_sm8150#1]

**Comment by gesangtome** [comment]
@VoidK2 
Thank you

**Comment by VoidK2** [comment]
> @VoidK2
> Thank you
现在进度怎么样

**Comment by gesangtome** [comment]
@VoidK2
Currently, OTA packets can be generated normally. However, the ZImage compiled using the kernel source of 'https://github.com/gesangtome/android_kernel_nubia_sm8150' still does not work, can enter the android launcher, crashes and then restarts automatically. Despite using various methods, I still didn't catch the key information of the crash, maybe because of the lack of drivers, I am not very clear, I can only wait for 'https://github.com/ztemt/NX627J_P_kernel' to release the latest again Try again after making changes.
